services:
  mysql-user:
    image: mysql
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
    ports:
      - "3307:3306"
    volumes:
      - user_data:/var/lib/mysql

  mysql-product:
    image: mysql
    container_name: mysql-product
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service
    ports:
      - "3308:3306"
    volumes:
      - product_data:/var/lib/mysql

  mysql-cart:
    image: mysql
    container_name: mysql-cart
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_service
    ports:
      - "3309:3306"
    volumes:
      - cart_data:/var/lib/mysql

volumes:
  user_data:
  product_data:
  cart_data:
