spring:
  datasource:
    url: jdbc:mysql://localhost:3309/cart_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka