spring:
  datasource:
    url: jdbc:mysql://localhost:3308/product_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka