spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka